INSERT INTO users (id, firstname, lastname, age) VALUES
    (1, 'FirstName1', 'LastName1', 19),
    (2, 'FirstName2', 'LastName2', 20),
    (3, 'FirstName3', 'LastName3', 21),
    (4, 'FirstName4', 'LastName4', 22),
    (5, 'FirstName5', 'LastName5', 23),
    (6, 'FirstName6', 'LastName6', 24),
    (7, 'FirstName7', 'LastName7', 25),
    (8, 'FirstName8', 'LastName8', 26),
    (9, 'FirstName9', 'LastName9', 27),
    (10, 'FirstName10', 'LastName10', 28),
    (11, 'FirstName11', 'LastName11', 29),
    (12, 'FirstName12', 'LastName12', 30),
    (13, 'FirstName13', 'LastName13', 31),
    (14, 'FirstName14', 'LastName14', 32),
    (15, 'FirstName15', 'LastName15', 33),
    (16, 'FirstName16', 'LastName16', 34),
    (17, 'FirstName17', 'LastName17', 35),
    (18, 'FirstName18', 'LastName18', 36),
    (19, 'FirstName19', 'LastName19', 37),
    (20, 'FirstName20', 'LastName20', 38);

INSERT INTO products (id, product_name, product_description, price_cents) VALUES
    (1, 'Product 1', 'Description for product 1. This is generated seed data for testing.', 637),
    (2, 'Product 2', 'Description for product 2. This is generated seed data for testing.', 774),
    (3, 'Product 3', 'Description for product 3. This is generated seed data for testing.', 911),
    (4, 'Product 4', 'Description for product 4. This is generated seed data for testing.', 1048),
    (5, 'Product 5', 'Description for product 5. This is generated seed data for testing.', 1185),
    (6, 'Product 6', 'Description for product 6. This is generated seed data for testing.', 1322),
    (7, 'Product 7', 'Description for product 7. This is generated seed data for testing.', 1459),
    (8, 'Product 8', 'Description for product 8. This is generated seed data for testing.', 1596),
    (9, 'Product 9', 'Description for product 9. This is generated seed data for testing.', 1733),
    (10, 'Product 10', 'Description for product 10. This is generated seed data for testing.', 1870),
    (11, 'Product 11', 'Description for product 11. This is generated seed data for testing.', 2007),
    (12, 'Product 12', 'Description for product 12. This is generated seed data for testing.', 2144),
    (13, 'Product 13', 'Description for product 13. This is generated seed data for testing.', 2281),
    (14, 'Product 14', 'Description for product 14. This is generated seed data for testing.', 2418),
    (15, 'Product 15', 'Description for product 15. This is generated seed data for testing.', 2555),
    (16, 'Product 16', 'Description for product 16. This is generated seed data for testing.', 2692),
    (17, 'Product 17', 'Description for product 17. This is generated seed data for testing.', 2829),
    (18, 'Product 18', 'Description for product 18. This is generated seed data for testing.', 2966),
    (19, 'Product 19', 'Description for product 19. This is generated seed data for testing.', 3103),
    (20, 'Product 20', 'Description for product 20. This is generated seed data for testing.', 3240);

INSERT INTO product_reviews (user_id, product_id, stars, review) VALUES
    (1, 1, 3, 'Decent product for the price.'),
    (2, 2, 4, 'Average experience. It works as expected.'),
    (3, 3, 5, 'Could be better, but overall I am satisfied.'),
    (4, 4, 1, 'Excellent product. Very satisfied with the purchase.'),
    (5, 5, 2, 'Good quality and arrived quickly.'),
    (6, 6, 3, 'Decent product for the price.'),
    (7, 7, 4, 'Average experience. It works as expected.'),
    (8, 8, 5, 'Could be better, but overall I am satisfied.'),
    (9, 9, 1, 'Excellent product. Very satisfied with the purchase.'),
    (10, 10, 2, 'Good quality and arrived quickly.'),
    (11, 11, 3, 'Decent product for the price.'),
    (12, 12, 4, 'Average experience. It works as expected.'),
    (13, 13, 5, 'Could be better, but overall I am satisfied.'),
    (14, 14, 1, 'Excellent product. Very satisfied with the purchase.'),
    (15, 15, 2, 'Good quality and arrived quickly.'),
    (16, 16, 3, 'Decent product for the price.'),
    (17, 17, 4, 'Average experience. It works as expected.'),
    (18, 18, 5, 'Could be better, but overall I am satisfied.'),
    (19, 19, 1, 'Excellent product. Very satisfied with the purchase.'),
    (20, 20, 2, 'Good quality and arrived quickly.');
